-- No unapplied production migrations at this time.
--
-- Last applied SQL Editor migration:
-- - migrations/010_check_in_session_ownership.sql
--
-- When preparing the next production rollout, replace this file with the
-- idempotent SQL bundle to paste into the Supabase SQL Editor.
